services:
  db:
    image: postgres:13
    container_name: education_performance
    restart: always
    environment:
      POSTGRES_DB: predicted_data.sql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: education_performance_app
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data: